### ISSUE TITLE
Killed process

### ISSUE THREAD

**Issue by joe-eis** [sumanth107/Restoration-Colorization-Enhancement-of-Images#2]
Thank you for your quick reply. I am very pleased with it.
I unfortunately have no knowledge about python programming, I'm more of a photo amateur with linux knowledge.

Unfortunately for me the installation is more complex than Bringing-Old-Photos-Back-to-Live and I almost give up.

I copied the model according to the READme instructions and linked the directories colorizer, Face_Enhancement and Global according to the Python library. 

Here is my output:

`
$ python3 run.py 
Initial Preprocessing Start
Initial Preprocessing Done
Running Restoration Step
Current Directory : /home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/test_images
Processing IMG_20220115_114302_weich.jpg

Traceback (most recent call last):
  File "detection.py", line 167, in <module>
    main(config)
  File "detection.py", line 137, in main
    P = torch.sigmoid(model(scratch_image_scale))
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/Global/detection_models/networks.py", line 107, in forward
    x = self.first(x)
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
Killed

Running Face Detection
Running Face Enhancement
Overall Restoration
Traceback (most recent call last):
  File "align_warp_back_multiple_dlib.py", line 397, in <module>
    blended = blur_blending_cv2(warped_back, blended, backward_mask)
  File "align_warp_back_multiple_dlib.py", line 191, in blur_blending_cv2
    mask *= 255.0
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
Running Colorization Step
Traceback (most recent call last):
  File "demo_release.py", line 27, in <module>
    img1 = load_img(os.path.join(opt.img_path, image_list_1[i][:-4] + '.png'))
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/colorizers/util.py", line 10, in load_img
    out_np = np.asarray(Image.open(img_path).convert('RGB'))
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/PIL/Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/upload_output/final_output/testimage.png'
Running Final Image Enhancement Step
/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py:144: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  warn('spsolve requires A be CSC or CSR matrix format',
enhancer.py:98: RuntimeWarning: invalid value encountered in power
  J = (I ** gamma) * beta

-----FINISHED-----

`

**Comment by sumanth107** [comment]
From the outputs, I think the project setup is fine. I believe this error occurs because Input type is 'torch.FloatTensor' and weight type 'torch.cuda.FloatTensor'. This occurred because the code involving pytorch has been written under the circumstances that CUDA isn't present. If what I suspect is true then appropriate changes must be made to account for this. Kindly check running the file after disabling CUDA.

**Comment by joe-eis** [comment]
I have switched to Intel graphics card. The outpt is a bit cleaner, but the process is probably killed. I do not get the photos in the output.

```
$ python3 run.py 
Initial Preprocessing Start
Initial Preprocessing Done
Running Restoration Step
Current Directory : /home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/test_images
Processing IMG_20220115_114302_weich.jpg
Processing Taube-Balkon_08.jpg
Processing ansel_adams2.jpg
Processing image (1).jpg
Processing lena_noisy.jpg
Processing lizard.jpg
Processing s1..jpg
Processing testimage.jpg

/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
Killed

Running Face Detection
Running Face Enhancement
Overall Restoration
Traceback (most recent call last):
  File "align_warp_back_multiple_dlib.py", line 397, in <module>
    blended = blur_blending_cv2(warped_back, blended, backward_mask)
  File "align_warp_back_multiple_dlib.py", line 191, in blur_blending_cv2
    mask *= 255.0
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
Running Colorization Step
Traceback (most recent call last):
  File "demo_release.py", line 27, in <module>
    img1 = load_img(os.path.join(opt.img_path, image_list_1[i][:-4] + '.png'))
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/colorizers/util.py", line 10, in load_img
    out_np = np.asarray(Image.open(img_path).convert('RGB'))
  File "/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/PIL/Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/upload_output/final_output/testimage.png'

Running Final Image Enhancement Step
/home/joern/tttest/Restoration-Colorization-Enhancement-of-Images/lib/python3.8/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py:144: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  warn('spsolve requires A be CSC or CSR matrix format',
enhancer.py:98: RuntimeWarning: invalid value encountered in power
  J = (I ** gamma) * beta

-----FINISHED-----
```

**Comment by sumanth107** [comment]
I see that the previous error has been mitigated by shifting to Intel graphics card. I would expect the program to give desired output now. I believe the 'killed' error is occurring probably due to your system constraints. Please check the stackoverflow [link](https://stackoverflow.com/questions/19189522/what-does-killed-mean-when-a-processing-of-a-huge-csv-with-python-which-sudde) discussing a similar issue.

**Comment by joe-eis** [comment]
Oops, i wouldn't have thought of that with my notebook with 16 GM RAM.

`Mar  4 13:31:36 M705 kernel: [   85.313395] Out of memory: Killed process 2591 (python) total-vm:18143348kB, anon-rss:15266384kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:31384kB oom_score_adj:0`

Many Thanks & best Regards
Jörn
